### ISSUE TITLE
Tree view example

### ISSUE THREAD

**Issue by alaneng** [reactabular/reactabular#168]
This is excellent -- exactly what I'm looking for and very intuitive. Thanks so much for working on this.

I'm looking to use this library for its TreeTable component. I'm looking at the source code for the component but can't figure out how the JSON data structure should look like when passing in subrows. What property would I pass into `rows`? An example would help illustrate this. 

Also, how would I incorporate TreeTable into this: `<Table.Body rows={rows} rowKey="id" />`? Would it be 
```
<Table.Provider>
  <TreeTable columns={columns} rows={rows} />
</Table.Provider>
```
?

Thanks again!

**Comment by bebraw** [comment]
I have to package the tree portion better. Maybe `reactabular-tree` with the [tree example](http://reactabular.js.org/#/examples/tree-view) utilities would work.

Take a good look at the schema:

```javascript
const schema = {
  type: 'object',
  properties: {
    id: {
      type: 'string'
    },
    name: {
      type: 'string'
    },
    age: {
      type: 'integer'
    }
  },
  required: ['id', 'name', 'age']
};
const rows = generateParents(generateRows(100, schema));
```

It generates essentially a flat list of items. `generateParents` assigns random `parent` relations so that the list is still ordered. You could have relations like this: 1 <-2, 2 <- 3, 2 <- 4, 2 <- 5... It has been designed this way on purpose so that I can keep the tree operations reasonably fast.

The solution still needs further optimization and I intend to spend time on that in the next few days. There are likely tweaks that can be done to push it further.

This isn't the only way you could handle a tree view. Perhaps a more popular approach would be to use a nested structure and end up with `children` relation. It would be interesting to see a variant based on a structure like this. You could still convert from here to a flat structure and vice versa.

> Also, how would I incorporate TreeTable into this: <Table.Body rows={rows} rowKey="id" />? Would it be

To answer your question, `<TreeTable columns={columns} rows={rows} />` won't work without tweaking. But you could extract a component like that out of the example quite easily. Perhaps that's something `reactabular-tree` should provide.

**Comment by alaneng** [comment]
Thanks. I saw the schema but wasn't sure how children rows are passed into the `rows` object. Would it be 
```
const rows = [
    {
    id: 100,
    name: 'John',
    country: 'fi', 
    children: {
       id: 200,
       name: 'Mary',
       country: 'dk', 
    }
  }
]
```
?

**Comment by bebraw** [comment]
It's literally a flat list. 😄 

```javascript
const rows = [
    {
    id: 100,
    name: 'John',
    country: 'fi'
  },
  {
    id: 200,
    name: 'Mary',
    country: 'fi',
    parent: 100
  }
]
```

The nice thing about this structure is that it fits the table rendering pipeline although I have to take care about visibility etc. outside of it. You also have to be very careful about the structure ordering as it expects to find parent above (not immediate necessarily) assuming the field has been set.

**Comment by foundationx** [comment]
I just want to be 100% sure, is it possible to have children that have different columns than the parent?

**Comment by bebraw** [comment]
@foundationx How would that work? Can you give example data?

**Comment by foundationx** [comment]
I don't know, I just wanted to make sure it was not currently possible to do, before I look for another solution. I have need for sub tables, but the columns are not the same.

**Comment by bebraw** [comment]
@foundationx I would need something visual to tell any better. I am not aware of other tables that support trees so most likely you'll need to whip up something custom to fit your needs.

**Comment by foundationx** [comment]
in sticking with the example I gave above, here is a visual
![1](https://cloud.githubusercontent.com/assets/1870288/21515527/d8478108-cc8d-11e6-99a1-35daf9842738.jpg)

**Comment by foundationx** [comment]
I probably have to do something custom, but just wanted to make sure I was not missing anything before I do that. Thanks

**Comment by bebraw** [comment]
@foundationx I think you can match the visual within the current system. Basically you need to manage some of that logic at the column definition to get those actors mapped.

An interesting alternative could be to skip using the tree functionality and build the functionality on top of a regular table. Then you would handle this logic with a transformer (capture open/close)/formatter (handle custom rendering).
