### ISSUE TITLE
Search with JS Object format,

### ISSUE THREAD

**Issue by hiteshpatwari** [reactabular/reactabular#181]
I have a column in my table which can be a String or a JS Object, but the issue is, if the value comes up as string, search is working properly. but does not work when it is a JSON like JS object.
here is my column definition : 

```
const TABLE_COLUMNS = [
  {
    cell: { property: 'id' },
    header: { label: 'id' }
  },
  {
    cell: {
      format: d => moment(d).format('YYYY-MM-DD HH:mm:ss'),
      property:'lastChanged'
    },
    header: { label: 'Last Changed' },
    search: d => moment(d).format('YYYY-MM-DD HH:mm:ss')
  },
  {
    header: { label: 'value' },
    cell: {
      format: v => <ValueCell value={ v } />,
      property: 'value'
    },
    search: v => JSON.stringify(v)
  }
]
```

I also tried, converting the JSON object to a array of strings and a comman separated string, both to no avail. what M I doing wrong here ?

**Comment by bebraw** [comment]
Hi,

The API has changed since the early betas. It doesn't do anything with `search` fields without effort. The search API supports resolver convention. See http://reactabular.js.org/#/resolving-data .

I think `byFunction` resolver should be what you need. You can define a custom field there and even map to `search` so it will pick up the value to search against from there.

Reading through the search package implementation and tests might give you even clearer idea.

I hope this helps.

**Comment by bebraw** [comment]
@hiteshpatwari Any luck with this? Can you set up a standalone example for me to study? Just pushed out 2.0 with some important tweaks.

**Comment by bebraw** [comment]
Closing due to lack of response.

Give the resolvers a go. I think that should fix your issue quite well.
