### ISSUE TITLE
reactabular-select - Add basic tests

### ISSUE THREAD

**Issue by bebraw** [reactabular/reactabular#184]
Test plan:

**byArrowKeys:**

* Up arrow pressed, no `selectedRowIndex` provided -> nothing should happen.
* Down arrow pressed, no `selectedRowIndex` provided -> nothing should happen.
* Up arrow pressed, `selectedRowIndex` provided and it's larger than zero -> `onSelectRow` should get called with `selectedRowIndex - 1`.
* Down arrow pressed, no `selectedRowIndex` provided and it's smaller than `rows` length - 1 -> `onSelectRow` should get called with `selectedRowIndex + 1`.

**selectRow:**

* Assuming `rows` contains `selected` flags and `isSelected` does not match any, all `selected` flags should become `false`.
* If `isSelected` matches a row, the resulting `rows` should have matching ones with the `selected` flag set as `true`. `selectRow` should also return `selectedRows` within an array (currently it returns just the last `selectedRow`!).

**Comment by git-toni** [comment]
I just implemented part of this, but after giving it a thought I would like to suggest a different approach.
If I understood correctly this is the *desired* (read not yet commited) behaviour now:

### selectRow
```javascript
//Current signature:
select.row({ rows: <rows>, isSelected: (row, selectedRowId) => <boolean>, 
                   selectedRowId: <any>}) => { rows: <rows>, selectedRow: <object> }
```
1. When no `rows` match the single value `selectedRowId` as described by `isSelected` ---> set all `rows[i].selected =false`.
2. Given a *single* value for `selectedRowId`, when `isSelected` returns one or more matches, set all those matching rows to `rows[i].selected=true`, and `.selected=false` all the rest. Return the matching rows in `selectedRows` instead of just the last one as it is currently deployed.

**Observations**
- Considering that `isSelected` is customizable - hence can operate irrespective of the actual row's `id` key -, wouldn't it be more appropiate to rename `selectedRowId` to something else? I can only think of `selectedRowKeyValue`, a bit long tho!

**The actual proposal of behavior**
Motivation: IMHO a quite common use-case is when one clicks on a row to select it, and can also re-click it to *un*-select it, a.k.a row selection toggle. This with the additional possibility of clicking (and selecting) different rows. Given these functionalities this would be some implementation details:

1. When no `rows` match the `selectedRowId` by `isSelected`, do nothing.
2. Whenever there is a match, toggle the `rows[i].selected` flag to the opposite of the current value.
3. Eliminate the return of `selectedRow/s`, simply based the logic on `rows` returning a new copy of it.

### new functions `selectAll`/`deselectAll`
```javascript 
//Signature:
select.selectAll({ rows: <rows>}) => { rows: <rows> } // all row[i].selected=true
select.deselectAll({ rows: <rows>}) => { rows: <rows> } // all row[i].selected=false
```
4. We would provide a `deselectAll` or `selectAll` functionality. I'm thinking that probably as a separate library function. This way the user can add a button/checkbox and pass it `onClick/change={select.selectAll.bind(this,rows)}` or something similar.

### byArrowKeys
Still not sure about this. If we do provide multi-select, then what happens when you are arrowing-down/up and stumble upon an already selected row? 
A. One approach would be to treat that "moving" row as an iterator/separate from the rest of the rows, but to me it feels over-complicating simple things. 
B. Maybe it should just jump over that selected row and pass to the next one?
C. Maybe it should be able to go beyond that selected one? As in can't cross a wall, that doesn't make a lot of intuitive sense...

Ok this comment ended up quite verbose :/

**Comment by bebraw** [comment]
> Considering that isSelected is customizable - hence can operate irrespective of the actual row's id key -, wouldn't it be more appropiate to rename selectedRowId to something else? I can only think of selectedRowKeyValue, a bit long tho!

I think we can drop `selectedRowId` from `select.row` signature without losing any value. So we'll end up with `select.row({ rows, isSelected })` kind of helper. That `isSelected` can then be used to match single or many. Essentially it performs a `map` operation over the row data and tracks which rows were selected. Not more than that.

> Motivation: IMHO a quite common use-case is when one clicks on a row to select it, and can also re-click it to un-select it, a.k.a row selection toggle. This with the additional possibility of clicking (and selecting) different rows. Given these functionalities this would be some implementation details:

Maybe some kind of `select.toggle` would work here. That would invert. Same mapping idea still.

> We would provide a deselectAll or selectAll functionality. I'm thinking that probably as a separate library function. This way the user can add a button/checkbox and pass it onClick/change={select.selectAll.bind(this,rows)} or something similar.

Yeah, `select.all`, `select.none` would work for me. All of these can use the same mapping kernel. Just that logic bit changes a notch.

> Still not sure about this. If we do provide multi-select, then what happens when you are arrowing-down/up and stumble upon an already selected row? 

I wouldn't worry about `select.byArrowKeys`. It's totally fine if we leave it as something you use with single selection for now. I guess ideally you would track key "cursor" separately and allow the user to define a function that specifies what happens when you hit up/down (select, deselect, toggle). This would allow you to implement a variety of behaviors.

---

Now that I think of it, `reactabular-select` could easily be extracted out of the core project (same as for `react-edit`). There's nothing Reactabular specific in selection after all.

I probably won't be able to work on this particular piece of functionality short term unless a client needs it, but I don't mind collaborating with a PR. Development-wise I would go like this:

1. Drop `selectedRowId` from `select.row`.
2. Extract selection kernel from `select.row` (the mapping part).
3. Implement `select.toggle`, `select.all`, `select.none` (same kernel, different logic).

That arrow key work feels like a separate PR to me as it needs some careful thought.

**Comment by bebraw** [comment]
> Given a single value for selectedRowId, when isSelected returns one or more matches, set all those matching rows to rows[i].selected=true, and .selected=false all the rest. Return the matching rows in selectedRows instead of just the last one as it is currently deployed.

Yeah, totally agreed. It would make more sense to return all the selected ones (multi-select case).

**Comment by git-toni** [comment]
> I think we can drop selectedRowId from select.row signature without losing any value.

Then I'm not sure I see the way `isSelected` will know about the currently `selectRowId`.
```javascript
// This is how we would call 'selectRow'
let myIsSelected=(row, selectedRowId) => ....

const result = selectRow({
      rows,
      myIsSelected
});

// Then somewhere at the 'selectRow' implementation
 if (isSelected(row, selectedRowId)) {
...
```
What do we send instead of `selectedRowId`?

> Maybe some kind of select.toggle would work here. That would invert. Same mapping idea still.
>Yeah, select.all, select.none would work for me. All of these can use the same mapping kernel. Just that logic bit changes a notch.

Great!

> I wouldn't worry about select.byArrowKeys. It's totally fine if we leave it as something you use with single selection for now. 

Ok, I have to look at it a bit more but I believe it may present a bit of incompatibility? Since `byArrowKeys` depends on `selectRow`. Additionaly I'm aware that `reactabular-easy` should also be edited to be compliant to future changes, since it uses `reactabular-edit`.

>Yeah, totally agreed. It would make more sense to return all the selected ones (multi-select case).

Does this mean that directly removing `selectedRows` out of the `return` and simply relying on `rows[].selected=true/false` as I suggested ( point 3 ) is not a convenient idea? If so, why? :)

> Now that I think of it, reactabular-select could easily be extracted out of the core project (same as for react-edit

Agree! And actually I've been playing a bit with my own approach to something similar to `react-edit`, inspired also by the jquery `x-editable` plugin ( which I used extensively in the past). I really like the way `react-edit` is designed tho.

On one hand quite surely there's a use for an isolated `react-edit`, on the other hand I can't picture now a situation where I would use something like `selectRow` in isolation ( unless I'm building my own table-system ofc!). What do you think?

Also, in the case one or both are isolated from the rest of reactabular, where would they live? A repository under **Reactabular** organization?

**Comment by bebraw** [comment]
> What do we send instead of selectedRowId?

`isSelected` would become something like `isSelected = row => row.id === selectedRow`. The way you match is up to you and the rule might look quite different depending on the case.

The current README example looking like this:

```javascript
onSelectRow(selectedRowIndex) {
  const { rows } = this.state;

  this.setState(
    select.row({
      rows,
      selectedRowId: rows[selectedRowIndex].id
    })
  );
}
```

would become

```javascript
onSelectRow(selectedRowIndex) {
  const { rows } = this.state;
  const selectedId = rows[selectedRowIndex].id;

  this.setState(
    select.row({
      rows,
      isSelected: ({ id }) => id === selectedId
    })
  );
}
```

in this scheme.

> Ok, I have to look at it a bit more but I believe it may present a bit of incompatibility? Since byArrowKeys depends on selectRow. Additionaly I'm aware that reactabular-easy should also be edited to be compliant to future changes, since it uses reactabular-edit.

Yeah. The `byArrowKeys` limitation could be documented. reactabular-easy needs to change, yup.

> Does this mean that directly removing selectedRows out of the return and simply relying on rows[].selected=true/false as I suggested ( point 3 ) is not a convenient idea? If so, why? :)

That's a good point. The API/implementation would be a little simpler if we didn't track selected rows while returning them separately.

If you look at the current README example, it makes good use of the returned selected row. Otherwise we would have to filter the data on the consumer side to figure out the same thing. Returning mapped rows (selection state updated) and selected rows (separate structure) seems like a good compromise.

> On one hand quite surely there's a use for an isolated react-edit, on the other hand I can't picture now a situation where I would use something like selectRow in isolation ( unless I'm building my own table-system ofc!). What do you think?

A lot of the table logic (search etc.) isn't tied to Reactabular. There are some convention based things but not that many. It's true people won't likely use the packages outside of this project, but it's at least fun to have some kind of logical boundaries there.

If/when something shinier than React comes along, we would need to re-implement only the view facing portions. 👍 

> Also, in the case one or both are isolated from the rest of reactabular, where would they live? A repository under Reactabular organization?

Correct. The generic bits would go below the same organization as I can't think of a more logical place. Maybe we can keep the development in this repository for now and fork later

**Comment by git-toni** [comment]
>Returning mapped rows (selection state updated) and selected rows (separate structure) seems like a good compromise.

>but it's at least fun to have some kind of logical boundaries there.
>If/when something shinier than React comes along, we would need to re-implement only the view facing portions. :+1:

Agreed!

>isSelected would become something like isSelected = row => row.id === selectedRow. The way you match is up to you and the rule might look quite different depending on the case.
 
I'm not sure this approach is preferable but I guess I need to test a few cases and see. Hopefully I'll work on this sometime this week, will update! :)

**Comment by git-toni** [comment]
`select.row` is actually quite a  basic component, but it would still be great to discuss a few approaches, specially  if it's gonna become an independent repository. 
IMO these are the four main options:

### Opt 1

Same as it is now, though implementing the return of multiple `selectedRows` as the only change.
**Pro:**
- No need to specify `isSelected`, it can be assumed to be ~`selectedRowId === row.id` (A very common use-case)

**Con:**
- Can't work with selections of different Id's - ie. `selectRowId` is a single value.
```javascript
onSelectRow(selectedRowIndex) {
  const { rows } = this.state;

  this.setState(
    select.row({
      rows,
      selectedRowId: rows[selectedRowIndex].id
    })
  );
}
```

### Opt 2
Removing `selectRowId`.
Pro
- One argument less, reduced API.

Con
- `isSelected` must be specified everytime, so it references the `selectedId` variable. 
- Subjective opinion: I believe there's more cognitive effort for the user in specifying `isSelected` each time. Eg. IMHO it's more straightforward to think it as a filter-by-Id by default than to pass the actual filter logic.
- If multiple `selectedId` at once would like to be allowed, the `isSelected` function becomes a bit lenghtier and thus less convenient to pass.
```javascript
onSelectRow(selectedRowIndex) {
  const { rows } = this.state;
  const selectedId = rows[selectedRowIndex].id;

  this.setState(
    select.row({
      rows,
      isSelected: ({ id }) => id === selectedId
    })
  );
}
```

### Opt 3
Extending `selectedRowId` to `selectedRowIds`.
Pro
- Allows multiple `Id` at once.
- `isSelected` can be assumed to be a filter by Id. (again, very common use-case)

Con
- API is still 3 params instead of one. Albeit providing more functionality.

```javascript
onSelectRow(selectedRowIndex) {
  const { rows } = this.state;
  const selectedId = rows[selectedRowIndex].id;

  this.setState(
    select.row({
      rows,
      selectedRowIds : [ 12, 23, 41 ] // Or just a single value "23"
    })
  );
}
```

### Opt 4
I believe a useful extension to **Opt 3** would be to use the same default `isSelected` logic just for other object attributes, eg. name. For that we could add a new argument, something like `selectionKey`(or `selectionAttr`), which would be used by `isSelected`.
This would leave the specification of `isSelected` only for those cases where the extraction of the data from each object is less trivial than a `get(attr)` + comparison against a value/array.
Additionally I'd probably name `selectedRowIds` something more appropiate like `selectedRowValues` or `selectedAttrValues`.

Pro
- Allows multiple values of  `Id`/`name`/`price` or whatever key at once.
- `isSelected` can be assumed to be a filter by that specified key(by default `selectionKey='id`).

Con
- API enlargement due to one more argument.

```javascript
onSelectRow(selectedRowIndex) {
  const { rows } = this.state;
  const selectedId = rows[selectedRowIndex].id;

  this.setState(
    //selects all rows with ram = 8 or 16
    select.row({
      rows,
      selectedRowValues : [ 8, 16 ], // Or just a single value "8"
      selectionKey: 'ram'
    })
  );
}
```

**Comment by bebraw** [comment]
Option 4 looks good to me. `selectionKey` could accept a function in addition to allow more exotic use cases (nested lookup or something like that). I would rewrite the signature as

```javascript
select.rows({
  rows,
  values: [8, 16],
  key: 'ram'
})
```

Or if we want to encode the selection idea a little differently:

```javascript
select.rows(
  row => [8, 16].includes(row.ram)
)(rows)
```

This would be more succinct while having the same power. I curried it because I use the same convention elsewhere and the idea composes well.

**Comment by git-toni** [comment]
I really like the second more succinct approach, plus the currying. However I may stick to the former one:
```javascript
select.rows({
  rows,
  values: [8, 16],
  key: 'ram'
})
```
Wouldn't you say it's a more straightforward signature to think of? Additionally we could add optional currying.

**Comment by bebraw** [comment]
I would go with the succinct one. Simply less API to remember since it's `select.rows(filter)(rows)`. And if you want, you can still write a verbose API on top of it. 👍 

`select.toggle` would fit into the same scheme. `select.all` and `select.none` would work without the filter.

So in the end a good API would look like this to me:

* `select.rows(filter)(rows)`
* `select.toggle(filter)(rows)`
* `select.all(rows)`
* `select.none(rows)`

There's still the problem of return value. In the existing design I return both `rows` and the selection. Any thoughts on that?

**Comment by git-toni** [comment]
Ok, settled then.
Wrt the returns, I'm convinced there's use for having the selection returned, as you cited a few comments abode with the example. Hence I'd stick to returning both.
The question is whether the `.selected` field in each row should be returned in the returned selected rows as well ( since it's a Reactabular-only attr)

**Comment by bebraw** [comment]
> Wrt the returns, I'm convinced there's use for having the selection returned, as you cited a few comments above with the example. Hence I'd stick to returning both.

Makes sense. My only problem is that it ties the implementation to specific field names. I would love to find a better pattern for handling the issue so that you can rename easily. Multiple returns are problematic.

> The question is whether the .selected field in each row should be returned in the returned selected rows as well ( since it's a Reactabular-only attr).

Might as well skip it, yeah.

**Comment by git-toni** [comment]
> Makes sense. My only problem is that it ties the implementation to specific field names. I would love to find a better pattern for handling the issue so that you can rename easily. Multiple returns are problematic.

Do you mean the user is tied to the specific return names (`rows`, `selectedRows`)? If so, get the concern, though I personally don't think it's such a big deal. One could easily rename in place:
```javascript
var {rows: allrows, selectedRows: myFavourieRows} = select.rows(...);
```
Another alternative is array destructuring, but that feels potentially messier:
```javascript
//returns [rows, selectedRows]
[allrows, myFavouriteRows] = select.rows(...)
```

**Comment by bebraw** [comment]
> Do you mean the user is tied to the specific return names (rows, selectedRows)? If so, I get the concern, though I personally don't think it's such a big deal. One could easily rename in place:

```javascript
var {rows: allrows, selectedRows: myFavouriteRows} = select.rows(...);
```

It's enough if we document that.

I set up a repository and shared rights if you want to start pushing. 👍

**Comment by git-toni** [comment]
Fantastic, will do asap :)

**Comment by bebraw** [comment]
@git-toni I set up two repos: [searchtabular](https://github.com/reactabular/searchtabular) and [selectabular](https://github.com/reactabular/selectabular). I'll push the search bit to the first one. Latter is for the selection bits.

**Comment by git-toni** [comment]
Great, I will start committing to the `selectabular` as soon as possible, will try to keep the `package.json` toolbox as close to reactabular as possible

**Comment by bebraw** [comment]
@git-toni Ok, cool. No need to use Lerna or anything. I'm thinking even vanilla Jest setup would be enough for testing. Also needs Babel for transpiling (copy the setup from individual packages at reactabular repo).

**Comment by git-toni** [comment]
Yup I was referring exactly at that basic config: jest + babel + eslint. I'm usually more on the side of ava/tape for tests, must confess I'm quite liking Jest :)

**Comment by bebraw** [comment]
Moved to [selectabular](https://github.com/reactabular/selectabular). Closing.

I'll probably remove selection bits from reactabular in the next major release and rewrite documentation accordingly.
