### ISSUE TITLE
Provide TypeScript type definitions?

### ISSUE THREAD

**Issue by bebraw** [reactabular/reactabular#187]
If anyone has any idea on how to achieve this neatly, comment on this issue.

**Comment by QuantumInformation** [comment]
Would you want to include in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by bebraw** [comment]
It would have to go there, yeah.

This is a huge task by itself and I won't be doing it unless the port can be funded somehow. Flow would be another direction (#188).

**Comment by bebraw** [comment]
This would be easier to pull off now that reactabular has been split up. I'm closing this issue, though, as I would need to find funding for that to happen.

**Comment by QuantumInformation** [comment]
Since you have complete control of the repo, I am now of the opinion that it's better to publish definition within your repository. Recently TypeScript has provided a way to autogenerate (--declaration option https://www.typescriptlang.org/docs/handbook/compiler-options.html) type definitions, which I have used in my repo (which is very simple use case). However, this only works if the original repo is written in ts.

https://github.com/quantumjs/solar-popup/blob/master/tsconfig.json#L6

**Comment by bebraw** [comment]
Yeah, it would be a fairly big amount of work, but it's good to know how it should go.
