### ISSUE TITLE
Examples CRUD with Redux, but with external API

### ISSUE THREAD

**Issue by scheung38** [reactabular/reactabular#225]
I like to use the Example CRUD with Redux, but instead of local data, I have API built using StrongLoop and so it would be helpful if there are examples to show how to use external data with CRUD?

**Comment by bebraw** [comment]
I could welcome an example like that if someone wants to contribute.

For now, check out [Redux documentation](http://redux.js.org/docs/advanced/). I think at minimum you'll want to hook up [redux-thunk](https://www.npmjs.com/package/redux-thunk). I have slides related to the topic at my [presentation about state management in React](https://presentations.survivejs.com/state-management-in-react/).

**Comment by git-toni** [comment]
I'm successfully integrating a CRUD-ish app using Reactabular.
In order to keep my Reactabular-based classes unconnected to Redux, I'm passing the actionCreators as props, and then calling them within `react-edit`'s `onValue` functions.

So, in case this can help you, if you look at [this](https://github.com/reactabular/reactabular/blob/master/docs/examples/multiple-async-instances.md) example in the Reactabular docs, or [here](http://reactabular.js.org/#/examples/multiple-async-instances) in the docs:

```javascript
//This instantiation of MyTable Reactabular-based class would be
<MyTable rows={tableA.rows} columns={tableA.columns}/>
//passed the actionCreator

let myActionCreator =(dispatch) =>... // somewhere in /src/actions/index.js

<MyTable rows={tableA.rows} columns={tableA.columns} itemCreatorAction={myActionCreator}/>
```

Then within `MyTable` definition I call that `itemCreatorAction` received as props:
```javascript
    onValue: ({ value, rowData, property }) => {
      const index = findIndex(this.state.rows, { id: rowData.id });
      const rows = cloneDeep(this.state.rows);

      rows[index][property] = value;
      rows[index].editing = false;

      this.setState({ rows });
      this.props.itemCreatorAction() //<---- Called here right after setting the state.
    }
```

In my case I'm using `react-edit`'s `onValue` as trigger, but you could use anything (buttons, selections, etc).
I'm quite happy with the results so far!

**Comment by bebraw** [comment]
Time to close. If someone wants to contribute some related documentation, please go ahead.
