### ISSUE TITLE
Horizontal scrolling causes header to get misaligned with body

### ISSUE THREAD

**Issue by dtaub** [reactabular/reactabular#282]
This is pretty easy to reproduce with the sticky example on the reactabular site by scrolling quickly to the right, then back to the left. The header gets misaligned with the body. Scrolling vertically realigns it so a possible hacky workaround is to programmatically force a vertical scroll to get it to re-render, but that's far from ideal.

I poked around the code a bit and didn't find any obvious fix for it but it's a fairly glaring issue.

Worth mentioning that this appears to be Chrome-specific. I can't reproduce this in Firefox; it looks like it works fine there. In Edge, horizontal scrolling doesn't really work, but that might be a separate issue.

**Comment by bebraw** [comment]
It's a tough one. The code relies on `onScroll` exposed by React. The problem is that there is no `onScrollEnd` or similar. What seems to happen is that not all scrolling is caught by the current handler that syncs the positions.

https://github.com/phazelift/react-scroll-listener seems to hack the end so that may be worth a look.

Earlier I tried managing `onScroll` at a table level (event bubbling). That killed performance completely, though.

If you can do a bit of research on this and point me to a stable direction, that would be great. A PR would be even better (pretty strapped on time + the project is not funded anymore).

**Comment by bebraw** [comment]
Here's the bubbling prototype btw, https://github.com/reactabular/reactabular/tree/sticky-ux .

**Comment by dtaub** [comment]
My initial thought was to realign it on some scrollEnd event, but alas as you said, that event doesn't natively exist. When I get a chance I'll try to look into it a bit more based on what you suggested.

**Comment by bebraw** [comment]
👍

It's a little weird, though, as it used to work a little better earlier. Maybe React has changed somehow. I can also drop context from the API (easy enough direction to try if you are interested). Maybe dropping the context would help with the even bubbling approach too. I never found out why it was so slow.

**Comment by dtaub** [comment]
I've yet to actually try implementing this in the code but just messing around in the browser console it looks like if we bypass React and use a raw DOM onscroll listener it works perfectly. Would there be any downside to that? I don't think the scroll position is something React necessarily needs to manage and once it's confirmed to work it seems like the simplest solution.

**Comment by bebraw** [comment]
Hi,

You could register/unregister that raw listener through React's lifecycle methods. If that works, great.

**Comment by redguardtoo** [comment]
See #259, an independent component `HorizontalScrollBar` solves the problem without any side effect.

I tested on Chrome/Firefox
