### ISSUE TITLE
Table not rerendering when state changes

### ISSUE THREAD

**Issue by cfteric** [reactabular/reactabular#355]
I have used controlled components to control a checkbox but as seen in the example, only the checkbox outside the table has been update to the new value.

Do I have to force a rerender somewhere to make the table show the updated value?

Here's an example to show what's going on: https://codesandbox.io/s/6joqxzkpxw

**Comment by bebraw** [comment]
Hi,

It's likely the SCU. See https://reactabular.js.org/#/table/overriding-should-component-update . You could try to override it as discussed there. First disable altogether to verify if this is the issue and then tune to match your use case.

If you can add the data to the row data somehow, that would fix it too due to the SCU.
