### ISSUE TITLE
Sort Strategy

### ISSUE THREAD

**Issue by thiagofernando** [reactabular/reactabular#383]
In your all features example, i cannot got work with  strategy: sort.strategies.byProperty.  (using your custom sort header)

Can you help me?

**Comment by bebraw** [comment]
Hi,

Can you upload your project on GitHub so I can have a better look? It's worth checking out the source of the strategies to see how they work underneath.

**Comment by thiagofernando** [comment]
thank you  to your rapid answer 

 https://github.com/thiagofernando/reactabular

**Comment by bebraw** [comment]
Looking at the code, I think the issue is that the property strategy isn't being applied to the sort header.

See https://github.com/reactabular/sortabular/blob/master/src/header.js for a reference. I would probably copy that as a starting point and then tune.

Note that to make your example work, I had to tune the uuid bit like this `import { v4 as uuid } from 'uuid';` also the calls became `uuid()` instead of `uuid.v4()` after this.

I think I would write a lot of the framework differently these days now that there are hooks for React. [react-table](https://www.npmjs.com/package/react-table) is perhaps the most supported table out there at the moment. As I don't have funding for mine at the moment, I am not giving it much attention these days.

**Comment by thiagofernando** [comment]
Thanks bebraw
